theme: jekyll-theme-slate

title: HyperProb
author: Oyendrila Dobe
email: dobeoyen@msu.edu
description: > # this means to ignore newlines until "baseurl:"
 User manual for the tool
# social links
github_username:  oyendrila-dobe # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

header_pages:
  - index.md
  - about.md
